import { Transaction } from '../../models/transaction.model';

export const w1Transctions: Transaction[] = [
  {
    time: 1575118800000,
    incoming: false,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.000023,
    hash: 'dfjsdljfsadjhfklsdfsdjncnvksdjfisdjfkldf',
    confirmations: 1,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Chaofan',
    recevierAddress: 'sjflkasdkflfsdfaskdfasdfasdf',
    description: 'a transaction from chaofan',
  },
  {
    time: 1578700800000,
    incoming: true,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.000019,
    hash: 'sdfjsdashjdfwohehbvasndalsfasdfadsfdsfdf',
    confirmations: 2,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Chaofan',
    recevierAddress: 'sdfasdfasdfslkjojdrhnqewlkfn',
    description: 'payment for aem',
  },
  {
    time: 1580475600000,
    incoming: false,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.000002,
    hash: 'fdsnvjnsdjpafhiaqhopajdvnjdnvkldmfdfjf',
    confirmations: 3,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Dee',
    recevierAddress: 'sdfalkjdfisdjfkhfkjdsfasdfasdfsd',
    description: 'a transaction dee paid ',
  },
  {
    time: 1584921600000,
    incoming: false,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.00081,
    hash: 'jdfbfdsjkfjsdfoiweuryethbdcjaksnfas',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    recevierAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
  },
  {
    time: 1586959200000,
    incoming: false,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.00081,
    hash: 'jdfbfdsjkfjsdfoiweuryethbdcjaksnfas',
    confirmations: 5,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Serin',
    recevierAddress: 'LJGMVKLFDSNSDJKFHAEFSDCDSFfghdfg',
    description: 'a transaction',
  },
  {
    time: 1589810400000,
    incoming: true,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.00081,
    hash: 'jdfbfdsjkfjsdfoiweuryethbdcjaksnfas',
    confirmations: 6,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Jakub',
    recevierAddress: 'xgksjdlfkjerhtndsnclaksdas',
    description: 'a transaction',
  },
];
