import { Transaction } from '../../models/transaction.model';
const rate = 0.1;
export const w5Transactions: Transaction[] = [
  {
    transId: 'dg3sdadasdfhyty',

    time: 1584921600000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    feeCrypto: 0.25,
    feeAud: 12,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    receiverAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
    ABN: 76839235556,
    tax: (rate * 10) / 1 + rate,
  },
  {
    transId: 'dg3sdad3sdfhyty',

    time: 1584921600000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    feeCrypto: 0.25,
    feeAud: 9,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    receiverAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
    ABN: 76839235556,
    tax: (rate * 10) / 1 + rate,
  },
  {
    transId: 'dg3sd5dasdfhyty',

    time: 1584921600000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    feeCrypto: 0.25,
    feeAud: 2,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    receiverAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
    ABN: 76839235556,
    tax: (rate * 10) / 1 + rate,
  },
  {
    transId: 'dg3sdad9sdfhyty',

    time: 1584921600000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    feeCrypto: 0.25,
    feeAud: 3,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    receiverAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
    ABN: 76839235556,
    tax: (rate * 10) / 1 + rate,
  },
  {
    transId: 'dg3sdadasd8hyty',

    time: 1586959200000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    feeCrypto: 0.25,
    feeAud: 5,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 5,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Serin',
    receiverAddress: 'LJGMVKLFDSNSDJKFHAEFSDCDSFfghdfg',
    description: 'a transaction',
    ABN: 76839235556,
    tax: (rate * 10) / 1 + rate,
  },
  {
    transId: 'dg3sdad7sdfhyty',

    time: 1589810400000,
    incoming: true,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    feeCrypto: 0.25,
    feeAud: 3,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 6,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Jakub',
    receiverAddress: 'xgksjdlfkjerhtndsnclaksdas',
    description: 'a transaction',
    ABN: 76839235556,
    tax: (rate * 10) / 1 + rate,
  },
];
