import { Transaction } from '../models/transaction.model';

export const transactions: Transaction[] = [
  //  ----------------- W1's transactions : sjdfasfl45asdfass454dfasdfsd : 6 : BTC no token transactions
  {
    time: 1575118800000,
    incoming: false,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.000023,
    hash: 'dfjsdljfsadjhfklsdfsdjncnvksdjfisdjfkldf',
    confirmations: 1,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Chaofan',
    recevierAddress: 'sjflkasdkflfsdfaskdfasdfasdf',
    description: 'a transaction from chaofan',
  },
  {
    time: 1578700800000,
    incoming: true,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.000019,
    hash: 'sdfjsdashjdfwohehbvasndalsfasdfadsfdsfdf',
    confirmations: 2,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Chaofan',
    recevierAddress: 'sdfasdfasdfslkjojdrhnqewlkfn',
    description: 'payment for aem',
  },
  {
    time: 1580475600000,
    incoming: false,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.000002,
    hash: 'fdsnvjnsdjpafhiaqhopajdvnjdnvkldmfdfjf',
    confirmations: 3,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Dee',
    recevierAddress: 'sdfalkjdfisdjfkhfkjdsfasdfasdfsd',
    description: 'a transaction dee paid ',
  },
  {
    time: 1584921600000,
    incoming: false,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.00081,
    hash: 'jdfbfdsjkfjsdfoiweuryethbdcjaksnfas',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    recevierAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
  },
  {
    time: 1586959200000,
    incoming: false,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.00081,
    hash: 'jdfbfdsjkfjsdfoiweuryethbdcjaksnfas',
    confirmations: 5,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Serin',
    recevierAddress: 'LJGMVKLFDSNSDJKFHAEFSDCDSFfghdfg',
    description: 'a transaction',
  },
  {
    time: 1589810400000,
    incoming: true,
    address: 'sjdfasfl45asdfass454dfasdfsd',
    fee: 0.25,
    amount: 0.00081,
    hash: 'jdfbfdsjkfjsdfoiweuryethbdcjaksnfas',
    confirmations: 6,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Jakub',
    recevierAddress: 'xgksjdlfkjerhtndsnclaksdas',
    description: 'a transaction',
  },

  //    ----------------  w2's transaction: jknlkasdfjaskdnfaksldfwieeesdf: 5: NEM

  {
    time: 1575118800000,
    incoming: false,
    address: 'jknlkasdfjaskdnfaksldfwieeesdf',
    fee: 0.25,
    amount: 0.000023,
    hash: 'dfjsdljfsadjhfklsdfsdjncnvksdjfisdjfkldf',
    confirmations: 1,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Chaofan',
    recevierAddress: 'sjflkasdkflfsdfaskdfasdfasdf',
    description: 'a transaction from chaofan',
  },
  {
    time: 1578700800000,
    incoming: true,
    address: 'jknlkasdfjaskdnfaksldfwieeesdf',
    fee: 0.25,
    amount: 0.000019,
    hash: 'sdfjsdashjdfwohehbvasndalsfasdfadsfdsfdf',
    confirmations: 2,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Chaofan',
    recevierAddress: 'sdfasdfasdfslkjojdrhnqewlkfn',
    description: 'payment for aem',
  },

  {
    time: 1584921600000,
    incoming: false,
    address: 'jknlkasdfjaskdnfaksldfwieeesdf',
    fee: 0.25,
    amount: 0.00081,
    hash: 'jdfbfdsjkfjsdfoiweuryethbdcjaksnfas',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    recevierAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
  },
  {
    time: 1586959200000,
    incoming: false,
    address: 'jknlkasdfjaskdnfaksldfwieeesdf',
    fee: 0.25,
    amount: 0.00081,
    hash: 'jdfbfdsjkfjsdfoiweuryethbdcjaksnfas',
    confirmations: 5,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Serin',
    recevierAddress: 'LJGMVKLFDSNSDJKFHAEFSDCDSFfghdfg',
    description: 'a transaction',
  },
  {
    time: 1589810400000,
    incoming: true,
    address: 'jknlkasdfjaskdnfaksldfwieeesdf',
    fee: 0.25,
    amount: 0.00081,
    hash: 'jdfbfdsjkfjsdfoiweuryethbdcjaksnfas',
    confirmations: 6,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Jakub',
    recevierAddress: 'xgksjdlfkjerhtndsnclaksdas',
    description: 'a transaction',
  },

  //    ------------- w3's transactions: dfjasdfjasldkfja34sldkfjlasfdfasdfa: 3 : ETH
  {
    time: 1584921600000,
    incoming: false,
    address: 'jknlkasdfjaskdnfaksldfwieeesdf',
    fee: 0.25,
    amount: 0.00081,
    hash: 'dfjasdfjasldkfja34sldkfjlasfdfasdfa',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    recevierAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
  },
  {
    time: 1586959200000,
    incoming: false,
    address: 'jknlkasdfjaskdnfaksldfwieeesdf',
    fee: 0.25,
    amount: 0.00081,
    hash: 'dfjasdfjasldkfja34sldkfjlasfdfasdfa',
    confirmations: 5,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Serin',
    recevierAddress: 'LJGMVKLFDSNSDJKFHAEFSDCDSFfghdfg',
    description: 'a transaction',
  },
  {
    time: 1589810400000,
    incoming: true,
    address: 'jknlkasdfjaskdnfaksldfwieeesdf',
    fee: 0.25,
    amount: 0.00081,
    hash: 'dfjasdfjasldkfja34sldkfjlasfdfasdfa',
    confirmations: 6,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Jakub',
    recevierAddress: 'xgksjdlfkjerhtndsnclaksdas',
    description: 'a transaction',
  },

  //    ------------- w4's transactions: fsdfahythdsasdf345erddfgdfsadfht: 3 : BTC

  //    ------------- w5's transactions: fsfgrtutyrrsewr675ewsasdffdhjtutuyeq: 6 : NEM

  {
    time: 1584921600000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    fee: 0.25,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    recevierAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
  },
  {
    time: 1584921600000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    fee: 0.25,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    recevierAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
  },
  {
    time: 1584921600000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    fee: 0.25,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    recevierAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
  },
  {
    time: 1584921600000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    fee: 0.25,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 4,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Sunny',
    recevierAddress: 'hgsaddavfutytsawASADSDFGSDJYSA',
    description: 'another transaction',
  },
  {
    time: 1586959200000,
    incoming: false,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    fee: 0.25,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 5,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Serin',
    recevierAddress: 'LJGMVKLFDSNSDJKFHAEFSDCDSFfghdfg',
    description: 'a transaction',
  },
  {
    time: 1589810400000,
    incoming: true,
    address: 'fsfgrtutyrrsewr675ewsasdffdhjtutuyeq',
    fee: 0.25,
    amount: 0.00081,
    hash: 'fsdfahythdsasdf345erddfgdfsadfht',
    confirmations: 6,
    // backend no this value
    amountAUD: 10,
    businessName: 'AEM',
    receiver: 'Jakub',
    recevierAddress: 'xgksjdlfkjerhtndsnclaksdas',
    description: 'a transaction',
  },
];
